#!/bin/bash

BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

function symlink {
  local source="${BASEDIR}/${1}"
  local target=$2

  ln -fs $source $target
}

function main {
  git submodule update --init --recursive

  # tmux
  symlink tmux.conf ~/.tmux.conf

  # git
  symlink gitconfig ~/.gitconfig

  # zsh
  symlink zshrc ~/.zshrc
  symlink cole.zsh-theme ~/.oh-my-zsh/themes
  symlink zsh-autosuggestions ~/.oh-my-zsh/custom/plugins
  symlink zsh-syntax-highlighting ~/.oh-my-zsh/custom/plugins

  # vim
  symlink vimrc ~/.vimrc
}

if [ "$1" == "--force" -o "$1" == "-f" ]; then
  main
else
  read -p "This may overwrite existing files. Are you sure? (y/N) "

  if [[ $REPLY =~ ^[Yy]$ ]]; then
    main
  else
    echo Aborted
  fi
fi


